export enum Coins {
  ARBITRUM = 'arbitrum',
  TRUEUSD = 'trueUSD',
  PANCAKE = 'pancake',
  E_ETH = 'eETH',
  WST_ETH = 'wstETH',
  ST_ETH = 'stETH',
  OPTIMISM = 'optimism',
  BSC = 'bsc',
  AAVE = 'aave',
  POLYGON = 'polygon',
  UNISWAP = 'uniswap',
  BNB = 'bnb',
  SOLANA = 'solana',
  ETHEREUM = 'ethereum',
  DAI = 'dai',
  BITCOIN = 'bitcoin',
  USDC = 'usdc',
  USDT = 'usdt',
}
