export enum Coins {
  ARBITRUM = 'arbittrum',
  TRUEUSD = 'trueUSD',
  PANCAKE = 'pancake',
  E_ETH = 'eETH',
  WST_ETH = 'wstETH',
  ST_ETH = 'stETH',
  OPTIMISM = 'optimism',
  BSC = 'BSC',
  AAVE = 'AAVE',
  POLYGON = 'polygon',
  UNISWAP = 'uniswap',
  BNB = 'BNB',
  SOLANA = 'solana',
  ETHEREUM = 'ethereum',
  DAI = 'DAI',
  BITCOIN = 'bitcoin',
  USDC = 'USDC',
  USDTF = 'USDTF',
}
