export const apis = {
  signup: '/auth/signup',
  login: '/auth/login',
  getUser: '/auth/user',
  stake: '/strategy/stake',
  halt: '/strategy/halt',
  info: '/strategy/getStakingInfo',
  getPools: '/strategy/pools',
  createWallet: '/wallet/create',
  getWallet: '/wallet/get',
  postFund: '/wallet/fund',
  getBalance: '/wallet/balance',
  postWithdraw: '/wallet/withdraw',
  getGraph: '/graph/get',
};
